### PR TITLE
Support PostgreSQL v15

### PR DESCRIPTION
**Pull request by fmbiete**
String is a PostgreSQL type, rename pljava String to PLJString

### CODE REVIEW

**Comment by pcnc** [comment]
@jcflack I gave it a test, it seems to be compiling and running as expected

**Comment by jcflack** [comment]
Thanks! My apologies, I've been consumed on other projects. I hope to resume work on this later in the week.

**Comment by tayalarun1** [comment]
The 2 files changes works good. Thanks for solving the issue.
Looking forward to incorporate this changes in release.

**Comment by df7cb** [comment]
Pulling this patch made the pljava Debian package compile against PG15.

**Comment by laserscout** [comment]
Would be great if this is merged soon

**Review by laserscout — APPROVED** [review]

**Comment by aadrian** [comment]
Any news on merging this?

**Comment by yrashk** [comment]
It looks like this fix resolves the problem. 👍

**Pull request closed without merging**
